Write a program to smooth the input image using:  
1. Averaging filter (un-weighted)
2. Weighted filter given by h(x,y)= max(|x|,|y|)
3. Gaussian filter
Note: Input the filter size and other parameters, such as sigma in case of Gaussian filter, method of padding (replication, zero padding, etc.) from the user.  

In [1]:
import cv2
import numpy as np
img = cv2.imread("wallpaper.jpg")
if img is None:
    print("Image not found!")
    exit()
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print("Choose filter:")
print("1. Averaging Filter")
print("2. Weighted Filter")
print("3. Gaussian Filter")

choice = int(input("Enter your choice: "))

ksize = int(input("Enter filter size (odd number, e.g. 3, 5, 7): "))

if ksize % 2 == 0:
    print("Filter size must be odd!")
    exit()
print("\nChoose padding method:")
print("1. Zero Padding")
print("2. Replication")
print("3. Reflection")

padding_choice = int(input("Enter padding choice: "))
if padding_choice == 1:
    border_type = cv2.BORDER_CONSTANT
elif padding_choice == 2:
    border_type = cv2.BORDER_REPLICATE
elif padding_choice == 3:
    border_type = cv2.BORDER_REFLECT
else:
    print("Invalid padding choice!")
    exit()
if choice == 1:
    kernel = np.ones((ksize, ksize), np.float32)
    kernel = kernel / (ksize * ksize)
    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )
    title = "Averaging Filter"
elif choice == 2:
    center = ksize // 2
    kernel = np.zeros((ksize, ksize), dtype=np.float32)
    for i in range(ksize):
        for j in range(ksize):
            x = i - center
            y = j - center
            kernel[i, j] = max(abs(x), abs(y))
    kernel_sum = np.sum(kernel)
    if kernel_sum != 0:
        kernel = kernel / kernel_sum

    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )
    title = "Weighted Filter"
elif choice == 3:
    sigma = float(input("Enter sigma value: "))
    result = cv2.GaussianBlur(
        img,
        (ksize, ksize),
        sigmaX=sigma,
        borderType=border_type
    )
    title = "Gaussian Filter"
else:
    print("Invalid filter choice!")
    exit()
cv2.imshow("Original Image", img)
cv2.imshow(title, result)
cv2.waitKey(0)
cv2.destroyAllWindows()

Choose filter:
1. Averaging Filter
2. Weighted Filter
3. Gaussian Filter


Enter your choice:  1
Enter filter size (odd number, e.g. 3, 5, 7):  3



Choose padding method:
1. Zero Padding
2. Replication
3. Reflection


Enter padding choice:  1


In [2]:
import cv2
import numpy as np
img = cv2.imread("wallpaper.jpg")
if img is None:
    print("Image not found!")
    exit()
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print("Choose filter:")
print("1. Averaging Filter")
print("2. Weighted Filter")
print("3. Gaussian Filter")

choice = int(input("Enter your choice: "))

ksize = int(input("Enter filter size (odd number, e.g. 3, 5, 7): "))

if ksize % 2 == 0:
    print("Filter size must be odd!")
    exit()
print("\nChoose padding method:")
print("1. Zero Padding")
print("2. Replication")
print("3. Reflection")

padding_choice = int(input("Enter padding choice: "))
if padding_choice == 1:
    border_type = cv2.BORDER_CONSTANT
elif padding_choice == 2:
    border_type = cv2.BORDER_REPLICATE
elif padding_choice == 3:
    border_type = cv2.BORDER_REFLECT
else:
    print("Invalid padding choice!")
    exit()
if choice == 1:
    kernel = np.ones((ksize, ksize), np.float32)
    kernel = kernel / (ksize * ksize)
    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )
    title = "Averaging Filter"
elif choice == 2:
    center = ksize // 2
    kernel = np.zeros((ksize, ksize), dtype=np.float32)
    for i in range(ksize):
        for j in range(ksize):
            x = i - center
            y = j - center
            kernel[i, j] = max(abs(x), abs(y))
    kernel_sum = np.sum(kernel)
    if kernel_sum != 0:
        kernel = kernel / kernel_sum

    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )
    title = "Weighted Filter"
elif choice == 3:
    sigma = float(input("Enter sigma value: "))
    result = cv2.GaussianBlur(
        img,
        (ksize, ksize),
        sigmaX=sigma,
        borderType=border_type
    )
    title = "Gaussian Filter"
else:
    print("Invalid filter choice!")
    exit()
cv2.imshow("Original Image", img)
cv2.imshow(title, result)
cv2.waitKey(0)
cv2.destroyAllWindows()

Choose filter:
1. Averaging Filter
2. Weighted Filter
3. Gaussian Filter


Enter your choice:  2
Enter filter size (odd number, e.g. 3, 5, 7):  5



Choose padding method:
1. Zero Padding
2. Replication
3. Reflection


Enter padding choice:  2


In [ ]:
import cv2
import numpy as np

# Read image
img = cv2.imread("wallpaper.jpg")

if img is None:
    print("Image not found!")
    exit()

# Convert to grayscale
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

print("Choose filter:")
print("1. Averaging Filter")
print("2. Weighted Filter")
print("3. Gaussian Filter")

choice = int(input("Enter your choice: "))

ksize = int(input("Enter filter size (odd number, e.g. 3, 5, 7): "))

if ksize % 2 == 0:
    print("Filter size must be odd!")
    exit()

print("\nChoose padding method:")
print("1. Zero Padding")
print("2. Replication")
print("3. Reflection")

padding_choice = int(input("Enter padding choice: "))

if padding_choice == 1:
    border_type = cv2.BORDER_CONSTANT
    padding_name = "Zero Padding"

elif padding_choice == 2:
    border_type = cv2.BORDER_REPLICATE
    padding_name = "Replication"

elif padding_choice == 3:
    border_type = cv2.BORDER_REFLECT
    padding_name = "Reflection"

else:
    print("Invalid padding choice!")
    exit()


# ------------------------------------------------
# 1. AVERAGING FILTER
# ------------------------------------------------

if choice == 1:

    kernel = np.ones((ksize, ksize), np.float32)
    kernel = kernel / (ksize * ksize)

    print("\n===== AVERAGING FILTER =====")
    print("Filter size:", ksize, "x", ksize)
    print("Padding:", padding_name)

    print("\nKernel:")
    print(kernel)

    print("\nCalculation:")
    print("Each pixel gets equal weight.")
    print("Weight of each pixel = 1 /", ksize * ksize)
    print("=", 1 / (ksize * ksize))

    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )

    title = "Averaging Filter"


# ------------------------------------------------
# 2. WEIGHTED FILTER
# ------------------------------------------------

elif choice == 2:

    center = ksize // 2

    kernel = np.zeros((ksize, ksize), dtype=np.float32)

    for i in range(ksize):
        for j in range(ksize):

            x = i - center
            y = j - center

            kernel[i, j] = max(abs(x), abs(y))

    kernel_sum = np.sum(kernel)

    if kernel_sum != 0:
        kernel = kernel / kernel_sum

    print("\n===== WEIGHTED FILTER =====")
    print("Filter size:", ksize, "x", ksize)
    print("Padding:", padding_name)

    print("\nKernel after normalization:")
    print(kernel)

    print("\nOriginal weight matrix:")

    original_kernel = np.zeros((ksize, ksize))

    for i in range(ksize):
        for j in range(ksize):

            x = i - center
            y = j - center

            original_kernel[i, j] = max(abs(x), abs(y))

    print(original_kernel)

    print("\nSum of weights =", kernel_sum)

    print("Normalized kernel:")
    print(original_kernel / kernel_sum)

    result = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=border_type
    )

    title = "Weighted Filter"


# ------------------------------------------------
# 3. GAUSSIAN FILTER
# ------------------------------------------------

elif choice == 3:

    sigma = float(input("Enter sigma value: "))

    print("\n===== GAUSSIAN FILTER =====")
    print("Filter size:", ksize, "x", ksize)
    print("Sigma:", sigma)
    print("Padding:", padding_name)

    # Generate Gaussian kernel
    kernel_1D = cv2.getGaussianKernel(ksize, sigma)

    kernel = kernel_1D @ kernel_1D.T

    print("\nGaussian Kernel:")
    print(kernel)

    print("\nSum of Gaussian kernel =", np.sum(kernel))

    result = cv2.GaussianBlur(
        img,
        (ksize, ksize),
        sigmaX=sigma,
        borderType=border_type
    )

    title = "Gaussian Filter"


else:
    print("Invalid filter choice!")
    exit()


# ------------------------------------------------
# SHOW ONE PIXEL CALCULATION
# ------------------------------------------------

center_y = img.shape[0] // 2
center_x = img.shape[1] // 2

half = ksize // 2

# Get neighborhood
neighborhood = img[
    center_y-half:center_y+half+1,
    center_x-half:center_x+half+1
]

print("\n================================")
print("SAMPLE PIXEL CALCULATION")
print("================================")

print("\nPixel neighborhood:")
print(neighborhood)

if choice == 1 or choice == 2 or choice == 3:

    # Calculate weighted sum
    calculation = neighborhood * kernel

    print("\nNeighborhood × Kernel:")
    print(calculation)

    value = np.sum(calculation)

    print("\nSum of all values =", value)

    print("Final output pixel =", round(value))

print("\n================================")
print("OUTPUT")
print("================================")

print("Original image size:", img.shape)
print("Filter:", title)
print("Filter size:", ksize, "x", ksize)
print("Padding:", padding_name)

if choice == 3:
    print("Sigma:", sigma)

print("Image smoothing completed!")

# Display images
cv2.imshow("Original Image", img)
cv2.imshow(title, result)

cv2.waitKey(0)
cv2.destroyAllWindows()

Choose filter:
1. Averaging Filter
2. Weighted Filter
3. Gaussian Filter


Enter your choice:  3
Enter filter size (odd number, e.g. 3, 5, 7):  7



Choose padding method:
1. Zero Padding
2. Replication
3. Reflection


Enter padding choice:  3
Enter sigma value:  2



===== GAUSSIAN FILTER =====
Filter size: 7 x 7
Sigma: 2.0
Padding: Reflection

Gaussian Kernel:
[[0.00492233 0.00919613 0.01338028 0.01516185 0.01338028 0.00919613
  0.00492233]
 [0.00919613 0.01718062 0.02499766 0.02832606 0.02499766 0.01718062
  0.00919613]
 [0.01338028 0.02499766 0.03637138 0.04121417 0.03637138 0.02499766
  0.01338028]
 [0.01516185 0.02832606 0.04121417 0.04670178 0.04121417 0.02832606
  0.01516185]
 [0.01338028 0.02499766 0.03637138 0.04121417 0.03637138 0.02499766
  0.01338028]
 [0.00919613 0.01718062 0.02499766 0.02832606 0.02499766 0.01718062
  0.00919613]
 [0.00492233 0.00919613 0.01338028 0.01516185 0.01338028 0.00919613
  0.00492233]]

Sum of Gaussian kernel = 0.9999999999999999

SAMPLE PIXEL CALCULATION

Pixel neighborhood:
[[50 50 50 50 50 51 53]
 [50 50 50 50 51 52 53]
 [50 50 51 52 53 53 54]
 [56 55 54 54 54 55 54]
 [60 59 57 55 54 54 53]
 [58 59 58 57 57 57 56]
 [53 53 54 55 58 60 63]]

Neighborhood × Kernel:
[[0.24611656 0.45980626 0.66901417 0.758092